#!/usr/bin/env python3
"""Keep generated parts of the documentation in step with the code.

    laika-docs.py --write    rewrite the generated blocks
    laika-docs.py --check    exit 1 if a block is out of date (the tests run this)

docs/configuration.md: the settings reference, from apps/api/settings_schema.py.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps/api"))
import settings_schema  # noqa: E402

DOC = ROOT / "docs/configuration.md"
START, END = "<!-- settings:start (generated by scripts/laika-docs.py) -->", "<!-- settings:end -->"
APPLY = {"live": "at once", "restart": "after **Apply now**", "host": "after **Apply now**"}


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def default_text(field):
    value = field["default"]
    if field["type"] == "bool":
        return "on" if value == "true" else "off"
    if value == "":
        return "—"
    if field["key"] == "MAX_WORKERS" and value == "0":
        return "0 (suggested)"
    return f"`{value}`"


def allowed(field):
    if field.get("choices"):
        labels = field.get("choice_labels") or {}
        return ", ".join(cell(labels.get(c, c)) for c in field["choices"])
    if "min" in field or "max" in field:
        return f"{field.get('min', '')}–{field.get('max', '')}"
    return ""


def settings_reference():
    lines = []
    for section, label, text in settings_schema.SECTIONS:
        fields = [f for f in settings_schema.FIELDS if f["section"] == section]
        if not fields:
            continue
        lines += [f"### {label}", "", text, "", "| Setting | Default | Allowed | Applies | Notes |", "| --- | --- | --- | --- | --- |"]
        for field in fields:
            lines.append(f"| {cell(field['label'])} | {default_text(field)} | {allowed(field)} | "
                         f"{APPLY.get(field['apply'], field['apply'])} | {cell(field.get('help', ''))} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render(text):
    block = f"{START}\n\n{settings_reference()}\n{END}"
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit(f"{DOC}: generated block markers missing")
    return pattern.sub(lambda _: block, text)


def main(argv):
    current = DOC.read_text()
    wanted = render(current)
    if "--write" in argv:
        DOC.write_text(wanted)
        return 0
    if wanted != current:
        print(f"{DOC} is out of date: run scripts/laika-docs.py --write", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
